# Data Types in Python

In Python there are four data types
booleans
integers
floats
strings


In [6]:
a=10
b=True
c="Python is cool"
d=1.3
#You could use type() function to check the type of the data object
type(a)

int

In [7]:
s="abcdefg"

print(s[0:2])
len(s)

ab


7

In [8]:
s="abcdefg"
s1=s[:-1]
print(s1)

abcdef


In [9]:
#To add strings together
a="Python "
b="is cool"
c=a+b
print(c)


Python is cool


In [10]:
a*3+b

'Python Python Python is cool'

# String management with index

To extract characters from the string in Python:
string[A:B:C]
where
A-the start position of the string
B-The position after the end part of the string
C: The step of the jumping from the start position towards the end
Note: the first character starts with 0 in the extraction 


In [11]:
letters="abcdefghijklmnopqrstuvwxyz"
#To extract the first three characters from the string
letters[::-1]


'zyxwvutsrqponmlkjihgfedcba'

In [12]:
letters="abcdefghijklmnopqrstuvwxyz"
letters[0:4:2]


'ac'

Quiz 1
Try the following statements:
len(letters)
letters[0]
letters[-1]
letters[0:2]
letters[0:4:2]
letters[::-1]
letters[:-1]

In [13]:
letters[:-1]

'abcdefghijklmnopqrstuvwxy'

You can also use "+" operator to perform the addition of strings

In [14]:
letters="abcdefghijklmnopqrstuvwxyz"
letters=letters+"A"
print(letters)


abcdefghijklmnopqrstuvwxyzA


In [15]:
letters[0]="b"

TypeError: 'str' object does not support item assignment

In [ ]:
letters="abcdefghijklmnopqrstuvwxyz"
letters="b"+letters[1:]
print(letters)

In [ ]:
letters="abcdefghijklmnopqrstuvwxyza"
letters1=letters.replace("a","b")
print(letters1)
print(letters1.strip("b"))
letters1


In [ ]:
#This is just a comment
data="1;2;4;6;8"
L1=data.split(";")
print(data)
print("L1=",L1)


In [ ]:
S1=','.join(L1)
print(S1)
type(S1)

In [ ]:
def menu(wine,entree,dessert):
    return {"wine":wine,"entree":entree,"dessert":dessert}



In [ ]:
d1=menu("chardonnav","chicken","cake")
print(d1)

# Basic data structures in Python

There are basically four data structures in Python:
-Lists
-Tuples
-Dictionaries
-Sets

## List

In [ ]:
L1=[[1,2,3],[4,5,6],[7,8,9]]
L2=L1[0][0:2]
print(L2)

In [ ]:
L1=[[1,2,3],[4,5,6],[7,8,9]]
L2=L1[0:2]
print(L2)

In [ ]:
L3=L1[::2]
print(L3)

In [ ]:
L3=L1[::2][1][0]
L3

In [ ]:
days=["1","2","3","4","5","6","7"]

print(days)
days.append("8")
print(days)
days.insert(1,"9")
print(days)
days.append(["8","9"])
print(days)
type(days)

In [ ]:
days=["1","2","3","4","5","6","7"]
days1=["8","9"]
days=days+days1
days

In [ ]:
days=["1","2","3","4","5","6","7"]
days1=["8","9"]
days=list(days[0])+days1+days[1:]
days

In [ ]:
days.extend(["10","11","12"])
print(days)

In [ ]:
days.index("1")
days.index("10")

In [1]:
#Note that with index method it will only return the first match
days=["1","2","3","4","1","5","6","7"]
days.index("1")

0

In [ ]:
days1=["13","14","15","16","17"]
days=days+days1
print(days)

In [ ]:
for i in [1,2,4,5,6]:
    print(i)

In [ ]:
L1=[1,2,3,4,6.7,9,11,100]
L2=[]
for i in L1:
    if i >=10:
        L2.append(i)
print(L2)

In [ ]:
#To search for the position of the list elements which match the filtering
#criteria.
L1=[1,2,1,2,3,4,5]
L2=[]
k=0
for i in L1:
    if i==1:
        L2.append(k)
    k=k+1
print(L2)
        
    
        
        

To remove elements from list object you could use the following ways:
-del function
-remove method
-pop method


In [ ]:
del days[len(days)-1]
print(days)
days.remove("16")
print(days)
t1=days.pop(2)
print("t1=",t1)
print("days=",days)

In [ ]:
days=["1","13","2","3","4","5","6","13","7"]
days.remove("13")
print(days)

The concept of mutable and immutable objects
In mutable objects reference is used for the variable assignment.
See example below:

In [ ]:
a=[1,2,4,5]
b=a
b[0]=2
print("b=",b)
print("a=",a)

In [ ]:
a=[1,2,4,5]
b=a.copy()
b[0]=2
print("b=",b)
print("a=",a)

### Use of list comprehesion

In [ ]:
list(range(1,6))

In [ ]:
L1=tuple(range(1,6))
print(L1)

In [ ]:
list(range(1,6))

In [ ]:
#Example to show how to generate a list with list comprehension
L2=[number for number in range(1,6) if number%2==1]
print(L2)


In [ ]:
L2=[]
for i in range(1,6):
    if i%2==1:
        L2.append(i)
print(L2)

In [ ]:
L1=[1,2,3,5,17,-1,10,11,12]


In [ ]:
#Another example to use list comprehension
L1=[1,2,3]
L2=[1,3,5,7,9,11]
L3=[i*2 for i in L2 if i in L1]
print(L3)

In [ ]:
L1=[1,2,3]
L2=[1,3,5,7,9,11]
L3=[]
for i in L2:
    if i in L1:
        L3.append(i*2)
print(L3)

In [ ]:
L1=[1,2,3,2,4,5,5,2]
L2=[2,5]
[i for i in L1 if i not in L2]


In [30]:
#To get the position of the list element where its value equals to 1
L1=[1,2,1,3,4]
[i for i in range(len(L1)) if L1[i]==1]

[0, 2]

## Tuple

In [ ]:
#To create tuple use the following methods:
t1=(1,)
type(t1)
t2=tuple([1,2,4])
print("t2=",t2)
print("Type of t2 is ",type(t2))


## Dictionary

In [ ]:
test1={"Monday":"Shopping","Tuesday":"Reading","Wednesday":"Sleeping","Thursday":"Working","Friday":"Reading"}
print("test1=",test1)

In [ ]:
print("The value for the key 'Monday' is ",test1["Monday"])

In [ ]:
test1["Monday"]="Sleeping"
print(test1)

In [ ]:
#To get the keys of the dictionary and store it as a separate list object:
list(test1.keys())
list(test1.values())
print("The keys in the dictionary are ",list(test1.keys()))
print("The values in the dictionary are ",list(test1.values()))


In [ ]:
#To add one more key value pair
test1["Saturday"]="Reading"
print(test1)
#To delete one particular key value pair
del test1["Saturday"]
print(test1)

In [ ]:
test2={"Monday":["Shopping","Running"],"Tuesday":["Reading"],
       "Wednesday":["Sleeping"],
       "Thursday":"Working","Friday":"Reading"}
test2

### Use of dictionary comprehension

In [17]:
list(test1.items())

[('Monday', 'Shopping'),
 ('Tuesday', 'Reading'),
 ('Wednesday', 'Sleeping'),
 ('Thursday', 'Working'),
 ('Friday', 'Reading')]

In [18]:
{item1:item2 for item1, item2 in test1.items() if item2=="Sleeping"}

{'Wednesday': 'Sleeping'}

In [19]:
print(test1)

[item1 for item1, item2 in test1.items() if item2=="Sleeping"]

{'Monday': 'Shopping', 'Tuesday': 'Reading', 'Wednesday': 'Sleeping', 'Thursday': 'Working', 'Friday': 'Reading'}


['Wednesday']

In [17]:
dict1={(1,2):[1,2,3,4],(2,3):[2,3,4,5,8],(3,4):[1,2,3,4,5,6]}

[item1 for item1,item2 in dict1.items() if len(item2)>5]

[(3, 4)]

In [18]:
list1=["Monday","Sunday"]
list2=["Sleeping","Sleeping"]
dict1=dict(zip(list1,list2))
print(dict1)


{'Monday': 'Sleeping', 'Sunday': 'Sleeping'}


In [20]:
list(zip(list1,list2))

[('Monday', 'Sleeping'), ('Sunday', 'Sleeping')]

In [47]:
L1=[1,2,3,2,3,5,6,6]
len(L1)==len(set(L1))

False

Quiz:
Filter out the weekdays where the task is reading and save it as a list object

In [22]:
test1.get("Monday","nothing")

'Sleeping'

In [23]:
test1.get("Sunday","nothing")

'nothing'

## Set

In [34]:
print(list(test1.values()))

set(list(test1.values()))

['Sleeping', 'Reading', 'Sleeping', 'Working', 'Reading']


{'Reading', 'Sleeping', 'Working'}

In [42]:
import sqlobject

# Use of NumPy package

In [32]:
import numpy as np
x2=np.array([[1,2,3],[4,5,6]])
print(x2)
type(x2)


[[1 2 3]
 [4 5 6]]


numpy.ndarray

In [3]:
print(x2.ndim)
print(x2.shape)
print(x2.size)

2
(2, 3)
6


In [4]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(np.concatenate([x,y]))
x3=np.vstack([x,y])
print(x3)
print(x3.shape)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [5]:
#Universal functions
x>y

array([False, False, False], dtype=bool)

In [24]:
x+y

array([5, 7, 9])

In [7]:
list(range(2,5))

[2, 3, 4]

In [8]:
[list(range(i,i+3)) for i in [2,4,6]]

[[2, 3, 4], [4, 5, 6], [6, 7, 8]]

In [10]:
L2=[]
for i in [2,4,6]:
    L2.append(list(range(i,i+3)))
L2

[[2, 3, 4], [4, 5, 6], [6, 7, 8]]

In [25]:
print([list(range(i,i+3)) for i in [2,4,6]])

x2=np.array([list(range(i,i+3)) for i in [2,4,6]])
print(x2)
x3=x2[:2,:2]
print(x3)
x4=x2[::2,::2]
print(x4)



[[2, 3, 4], [4, 5, 6], [6, 7, 8]]
[[2 3 4]
 [4 5 6]
 [6 7 8]]
[[2 3]
 [4 5]]
[[2 4]
 [6 8]]


In [36]:
x2=np.array([list(range(i,i+3)) for i in [2,4,6]])
x3=x2[:2,1:]
x3

array([[3, 4],
       [5, 6]])

In [14]:
x2=np.array([list(range(i,i+5)) for i in [2,4,6]])
print(x2)
x3=x2[:2,:3]
x3

[[ 2  3  4  5  6]
 [ 4  5  6  7  8]
 [ 6  7  8  9 10]]


array([[2, 3, 4],
       [4, 5, 6]])

In [16]:
print(x2)

x3=x2[::2,1]
print(x3)

print(x3.shape)

x4=list(x2[::2,1])
print(x4)

[[ 2  3  4  5  6]
 [ 4  5  6  7  8]
 [ 6  7  8  9 10]]
[3 7]
(2,)
[3, 7]


In [17]:
x2=np.array([list(range(i,i+3)) for i in [2,4,6]])
print(x2)
print()
x3=x2[:2,:2]
print(x3)
print()

x3[0,0]=20
print(x3)
print()
print(x2)

[[2 3 4]
 [4 5 6]
 [6 7 8]]

[[2 3]
 [4 5]]

[[20  3]
 [ 4  5]]

[[20  3  4]
 [ 4  5  6]
 [ 6  7  8]]


In [10]:
x2=np.array([list(range(i,i+3)) for i in [2,4,6]])
print(x2)
print()
x3=x2[:2,:2].copy()
print(x3)
print()

x3[0,0]=20
print(x3)
print()
print(x2)

[[2 3 4]
 [4 5 6]
 [6 7 8]]

[[2 3]
 [4 5]]

[[20  3]
 [ 4  5]]

[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [25]:
array1=np.arange(1,10)
print(array1)
type(array1)
array1.shape
array1.ndim
grid = np.arange(1, 10).reshape((3, 3))
grid

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
x2=np.array([list(range(i,i+3)) for i in [2,4,6]])
print(x2)
x4=x2.reshape(1,9)
x4

[[2 3 4]
 [4 5 6]
 [6 7 8]]


array([[2, 3, 4, 4, 5, 6, 6, 7, 8]])

## Use of Pandas

In [56]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data)

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64


In [32]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],index=["a","b","c","d"])
print(data)

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64


In [57]:
import pandas as pd
data = pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])
data>0.6

a    False
b    False
c     True
d     True
dtype: bool

In [27]:
import pandas as pd
data = pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])
data>0.6
data[data>0.6]

c    0.75
d    1.00
dtype: float64

In [58]:
data.iloc[0:2]


a    0.25
b    0.50
dtype: float64

In [59]:
data.loc[["a","c"]]

a    0.25
c    0.75
dtype: float64

In [28]:
import pandas as pd
L1=[1,3,5,4,6,7,8,10,100,102]
S1=pd.Series(L1,index=["a","b","c","d","e","f","g","h","i","j"])
S1[S1>=100]
S1.iloc[8:10]
S1.loc["i":"j"]
S1.loc[["i","j"]]



i    100
j    102
dtype: int64

In [41]:
#There are two ways of filtering on pandas's series or dataframe object
data = pd.Series([0.25,0.5,0.75,1.0],index=['a','b','c','d'])
print(data)
#method 1: by masking
#It will filter based on the index values of the return 
#boolean series object
data[data>0.6]
#Method 2: By slicing position
data.iloc[0:2]
#Method 3: by index 

data.loc["b":"c"]
                                               
                                               



a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64


b    0.50
c    0.75
dtype: float64

In [30]:
import pandas as pd
Dict1={"A1":1,"A2":2,"A3":3,"A4":4}
ID=pd.Series(Dict1)
ID

A1    1
A2    2
A3    3
A4    4
dtype: int64

In [32]:
#Exercise
#Create the dataframe for the following dictionaries:
#column name for Dict1 is "ID"
#column namne for Dict2 is "Name"
#column name for Dict3 is "Income"
import pandas as pd
Dict1={"A1":1,"A2":2,"A3":3,"A4":4}
Dict2={"A1":"Peter","A2":"Victor","A3":"Albert","A4":"Alice"}
Dict3={"A1":1000,"A2":20000,"A3":3000,"A4":4000}
Dict4={"A1":"Lee","A2":"Chan","A3":"Tam","A4":"Cheung"}

ID=pd.Series(Dict1)
First_Name=pd.Series(Dict2)
Income=pd.Series(Dict3)
Last_Name=pd.Series(Dict4)
df=pd.DataFrame({"ID":ID,"First_Name":First_Name,
                 "Income":Income,"Last_Name":Last_Name})

df["Full_Name"]=df["First_Name"]+" "+df["Last_Name"]

df


First_Name  ID  Income Last_Name     Full_Name
A1      Peter   1    1000       Lee     Peter Lee
A2     Victor   2   20000      Chan   Victor Chan
A3     Albert   3    3000       Tam    Albert Tam
A4      Alice   4    4000    Cheung  Alice Cheung

In [61]:
import pandas as pd
Dict1={"A1":1,"A2":2,"A3":3,"A4":4}
ID=pd.Series(Dict1)
ID

A1    1
A2    2
A3    3
A4    4
dtype: int64

In [55]:
df[df.Income<3000]

First_Name  ID  Income Last_Name Full_Name
A1      Peter   1    1000        10  Peter 10

In [65]:
import pandas as pd
Dict1={"A1":1,"A2":2,"A3":3,"A4":4}
Dict2={"A1":"Peter","A2":"Victor","A3":"Albert","A4":"Alice"}
Dict3={"A1":1000,"A2":20000,"A3":3000,"A4":2000}
Dict4={"A1":"Lee","A2":"Chan","A3":"Tam","A4":"Cheung"}

ID=pd.Series(Dict1)
First_Name=pd.Series(Dict2)
Income=pd.Series(Dict3)
Last_Name=pd.Series(Dict4)
df=pd.DataFrame({"ID":ID,"First_Name":First_Name,
                 "Income":Income,"Last_Name":Last_Name})
df

First_Name  ID  Income Last_Name
A1      Peter   1    1000       Lee
A2     Victor   2   20000      Chan
A3     Albert   3    3000       Tam
A4      Alice   4    2000    Cheung

In [71]:
list(df[df.Income<=3000]["First_Name"].values)

['Peter', 'Albert', 'Alice']

In [64]:
#Exercise
#Create the dataframe for the following dictionaries:
#column name for Dict1 is "ID"
#column namne for Dict2 is "Name"
#column name for Dict3 is "Income"
import pandas as pd
Dict1={"A1":1,"A2":2,"A3":3,"A4":4}
Dict2={"A1":"Peter","A2":"Victor","A3":"Albert","A4":"Alice"}
Dict3={"A1":1000,"A2":20000,"A3":3000,"A4":2000}
Dict4={"A1":"Lee","A2":"Chan","A3":"Wu","A4":"Tam"}

ID=pd.Series(Dict1)
First_Name=pd.Series(Dict2)
Income=pd.Series(Dict3)
Last_Name=pd.Series(Dict4)
df=pd.DataFrame({"ID":ID,"First_Name":First_Name,
                 "Income":Income,"Last_Name":Last_Name})

df["Last_Name"]=df["Last_Name"].astype(str)

df["Full_Name"]=df["First_Name"]+" "+df["Last_Name"]

df

First_Name  ID  Income Last_Name    Full_Name
A1      Peter   1    1000       Lee    Peter Lee
A2     Victor   2   20000      Chan  Victor Chan
A3     Albert   3    3000        Wu    Albert Wu
A4      Alice   4    4000       Tam    Alice Tam

In [33]:
import pandas as pd
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)

print(population)

area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)

states = pd.DataFrame({'population': population,
                       'area': area})

print(states)

California    38332521
Florida       19552860
Illinois      12882135
New York      19651127
Texas         26448193
dtype: int64
              area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193


In [34]:
#You could just add one extra column with the following method:
states["density"]=states["area"]/states["population"]
print(states)

              area  population   density
California  423967    38332521  0.011060
Florida     170312    19552860  0.008710
Illinois    149995    12882135  0.011644
New York    141297    19651127  0.007190
Texas       695662    26448193  0.026303


In [29]:
print(states)
states=states[["density","area"]]
print(states)

              area  population   density
California  423967    38332521  0.011060
Florida     170312    19552860  0.008710
Illinois    149995    12882135  0.011644
New York    141297    19651127  0.007190
Texas       695662    26448193  0.026303
             density    area
California  0.011060  423967
Florida     0.008710  170312
Illinois    0.011644  149995
New York    0.007190  141297
Texas       0.026303  695662


In [36]:
#To filter the dataframe such that the area is >=150000. 
#To display only the population and the area columns

states[states.area>=150000][["population","area"]]


population    area
California    38332521  423967
Florida       19552860  170312
Texas         26448193  695662

In [36]:
print(states)
states=states.loc[["New York","Texas"]]
print(states)

             density    area
California  0.011060  423967
Florida     0.008710  170312
Illinois    0.011644  149995
New York    0.007190  141297
Texas       0.026303  695662
           density    area
New York  0.007190  141297
Texas     0.026303  695662


In [24]:
states

print(states.density>0.01)

states[states.density>0.01]

California     True
Florida       False
Illinois       True
New York      False
Texas          True
Name: density, dtype: bool


area  population   density
California  423967    38332521  0.011060
Illinois    149995    12882135  0.011644
Texas       695662    26448193  0.026303

In [37]:
#If we need to filter out the dataframe where the area>200000

states[states.area>200000]


area  population   density
California  423967    38332521  0.011060
Texas       695662    26448193  0.026303

In [27]:
np.logical_and(states.density<0.02,states.area>200000)

states[np.logical_and(states.density<0.02,states.area>200000)]

area  population  density
California  423967    38332521  0.01106

In [14]:
#You could easily remove column with drop method and specify axis=1
states=states.drop("density",axis=1)
print(states)

              area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193


In [15]:
states.head()

area  population
California  423967    38332521
Florida     170312    19552860
Illinois    149995    12882135
New York    141297    19651127
Texas       695662    26448193

In [40]:
states.head()
L11=states.describe()
L11

area    population   density
count       5.000000  5.000000e+00  5.000000
mean   316246.600000  2.337337e+07  0.012981
std    242437.411951  9.640386e+06  0.007660
min    141297.000000  1.288214e+07  0.007190
25%    149995.000000  1.955286e+07  0.008710
50%    170312.000000  1.965113e+07  0.011060
75%    423967.000000  2.644819e+07  0.011644
max    695662.000000  3.833252e+07  0.026303

In [49]:
type(L11)
L11.index
L2=L11.loc["75%"][["area"]]
L2

area    423967.0
Name: 75%, dtype: float64

In [61]:
states.index
states.values

array([[  423967, 38332521],
       [  170312, 19552860],
       [  149995, 12882135],
       [  141297, 19651127],
       [  695662, 26448193]], dtype=int64)

In [50]:
df1=pd.DataFrame({"A1":[1,2,3,4,5],"A2":[2,3,4,6,7]})
print(df1)
df2=pd.DataFrame({"A3":[1,2,3,4,5],"A4":[2,3,4,6,7]})
print(df2)
df3=pd.concat([df1,df2],axis=1)
#To change the column names of the data frame in pandas
df3.columns=["A11","A12","A13","A14"]
print(df3)



   A1  A2
0   1   2
1   2   3
2   3   4
3   4   6
4   5   7
   A3  A4
0   1   2
1   2   3
2   3   4
3   4   6
4   5   7
   A11  A12  A13  A14
0    1    2    1    2
1    2    3    2    3
2    3    4    3    4
3    4    6    4    6
4    5    7    5    7


In [67]:
df3.columns.values[0]="A"
df3

A  A12  A13  A14
0  1    2    1    2
1  2    3    2    3
2  3    4    3    4
3  4    6    4    6
4  5    7    5    7

In [56]:
df1=pd.DataFrame({"A1":[1,2,3,4,5],"A2":[2,3,4,6,7]})
print(df1)
df2=pd.DataFrame({"A3":[1,2,3,4,5],"A4":[2,3,4,6,7]},index=[5,6,7,8,9])
print(df2)
df3=pd.concat([df1,df2],axis=1)
#To change the column names of the data frame in pandas
df3.columns=["A11","A12","A13","A14"]
print(df3)

   A1  A2
0   1   2
1   2   3
2   3   4
3   4   6
4   5   7
   A3  A4
5   1   2
6   2   3
7   3   4
8   4   6
9   5   7
   A11  A12  A13  A14
0  1.0  2.0  NaN  NaN
1  2.0  3.0  NaN  NaN
2  3.0  4.0  NaN  NaN
3  4.0  6.0  NaN  NaN
4  5.0  7.0  NaN  NaN
5  NaN  NaN  1.0  2.0
6  NaN  NaN  2.0  3.0
7  NaN  NaN  3.0  4.0
8  NaN  NaN  4.0  6.0
9  NaN  NaN  5.0  7.0


In [58]:
#If you want to extract the column names of the data frame and assign it to 
#another list object
L3=list(df3.columns)

['A1', 'A2', 'A3', 'A4']

In [57]:
df4=pd.concat([df1,df2])
print(df4)


    A1   A2   A3   A4
0  1.0  2.0  NaN  NaN
1  2.0  3.0  NaN  NaN
2  3.0  4.0  NaN  NaN
3  4.0  6.0  NaN  NaN
4  5.0  7.0  NaN  NaN
0  NaN  NaN  1.0  2.0
1  NaN  NaN  2.0  3.0
2  NaN  NaN  3.0  4.0
3  NaN  NaN  4.0  6.0
4  NaN  NaN  5.0  7.0


### To filter on data frame in pandas

### Deal with missing values in data frame

In [72]:
a=pd.Series({"a":1,"b":2,"c":None,"d":10})
print(a)
list(a[a.isnull()].index)

a     1.0
b     2.0
c     NaN
d    10.0
dtype: float64


['c']

In [69]:
#To check the number of missing values in the series
a=pd.Series({"a":1,"b":2,"c":None,"d":10,"e":None})
a.isnull().sum()

2

In [18]:
a=pd.Series({"a":1,"b":2,"c":None,"d":10})
print(a)
print()
print(a[a.isnull()].index)
print()
print(a[a.notnull()])



a     1.0
b     2.0
c     NaN
d    10.0
dtype: float64

Index(['c'], dtype='object')

a     1.0
b     2.0
d    10.0
dtype: float64


In [17]:
a=pd.Series({"a":1,"b":2,"c":None,"d":10})
print(a)
print()
print(a.isnull())
print()



a     1.0
b     2.0
c     NaN
d    10.0
dtype: float64

a    False
b    False
c     True
d    False
dtype: bool



Now we have included one more state here in the dictionary:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995,'Hawaii':10000}
No update of the population dictionary however.
Try to recreate the data frame from above.
Have you found something different than before ?
How to retrieve the state where the population is missing in the data frame ?


In [70]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995,'Hawaii':10000}
area = pd.Series(area_dict)

population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)


states1 = pd.DataFrame({'population': population,
                       'area': area})
print(states1)

states1[states1.population.isnull()].index

print("The distict name where the population is missing is",\
      list(states1[states1.population.isnull()].index)[0])

              area  population
California  423967  38332521.0
Florida     170312  19552860.0
Hawaii       10000         NaN
Illinois    149995  12882135.0
New York    141297  19651127.0
Texas       695662  26448193.0
The distict name where the population is missing is Hawaii


In [30]:
list(states1[states1.population.isnull()].index)

['Hawaii']

In [64]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995,'Hawaii':10000,"AA":20000}
area = pd.Series(area_dict)

population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)


states1 = pd.DataFrame({'population': population,
                       'area': area})
print(states1)

L1=list(states1[states1.population.isnull()].index)

print(L1)

print("The name of the states where the poulation is missing are: ",",".join(L1))


              area  population
AA           20000         NaN
California  423967  38332521.0
Florida     170312  19552860.0
Hawaii       10000         NaN
Illinois    149995  12882135.0
New York    141297  19651127.0
Texas       695662  26448193.0
['AA', 'Hawaii']
The name of the states where the poulation is missing are:  AA,Hawaii


### To imputate missing values per column by the median value of each column

In [71]:
print(states1)
print(states1.median())
states1.fillna(states1.median(),inplace=True)
print(states1)

              area  population
California  423967  38332521.0
Florida     170312  19552860.0
Hawaii       10000         NaN
Illinois    149995  12882135.0
New York    141297  19651127.0
Texas       695662  26448193.0
area            160153.5
population    19651127.0
dtype: float64
              area  population
California  423967  38332521.0
Florida     170312  19552860.0
Hawaii       10000  19651127.0
Illinois    149995  12882135.0
New York    141297  19651127.0
Texas       695662  26448193.0


### Exercise 

In [73]:
import os
os.getcwd()
os.chdir("E:/R_Working_Directory")
os.getcwd()

'E:\\R_Working_Directory'

In [74]:
data=pd.read_csv("TrainingData_latest.csv",sep=";")
data.shape

(13949, 22)

In [76]:
data.describe()

ID   NumComplains   RACH_Setup_Completion_Success_Rate_AVG  \
count  13949.000000   13949.000000                             13948.000000   
mean    6975.000000       0.111764                                 0.986888   
std     4026.873787       0.315088                                 0.031489   
min        1.000000       0.000000                                 0.325024   
25%     3488.000000       0.000000                                 0.988516   
50%     6975.000000       0.000000                                 0.995874   
75%    10462.000000       0.000000                                 0.998561   
max    13949.000000       1.000000                                 1.000012   

        Total_RRC_Connection_Setup_Success_Ratio_AVG  \
count                                   13947.000000   
mean                                        0.998041   
std                                         0.003141   
min                                         0.857417   
25%                                         0.997722   
50%                                         0.998739   
75%                                         0.999361   
max                                         1.000970   

        Total_RRC_Connection_Re_establishment_Success_Ratio_AVG  \
count                                       13538.000000          
mean                                            0.480027          
std                                             0.221058          
min                                             0.005460          
25%                                             0.316334          
50%                                             0.451478          
75%                                             0.634576          
max                                             1.000000          

        Radio_Bearer_Success_Ratio_AVG   ERAB_SetupSR_AVG  \
count                     13947.000000       13947.000000   
mean                          0.998881           0.999173   
std                           0.002354           0.004461   
min                           0.862952           0.793300   
25%                           0.998856           0.999444   
50%                           0.999318           0.999740   
75%                           0.999584           0.999892   
max                           1.000000           1.003578   

        HO_Success_Ratio_intra_eNB_AVG   Average_CQI_AVG  \
count                     13799.000000      13948.000000   
mean                          0.991812          9.757671   
std                           0.017259          1.301091   
min                           0.500000          4.929429   
25%                           0.991108          8.934675   
50%                           0.996186          9.616314   
75%                           0.998936         10.400963   
max                           1.000802         14.856340   

        Radio_Bearer_Drop_Ratio_AVG  \
count                  13569.000000   
mean                       0.004751   
std                        0.018849   
min                        0.000110   
25%                        0.000967   
50%                        0.001812   
75%                        0.003731   
max                        1.000000   

        Average_Physical_Resource_Block_Usage_UL_AVG  \
count                                   13869.000000   
mean                                        1.710451   
std                                         2.333754   
min                                         0.025000   
25%                                         0.367647   
50%                                         0.981092   
75%                                         2.200536   
max                                        60.965000   

        Average_Physical_Resource_Block_Usage_DL_AVG  \
count                                   13949.000000   
mean                                       11.118822   
std                                        10.667966   
min                     

In [77]:
data.head()

ID   NumComplains          hour_id      LCID  \
0   1              1  11/20/2015 0:03  33378111   
1   2              1  11/20/2015 0:27  23596112   
2   3              1  11/20/2015 0:29  10611113   
3   4              1  11/20/2015 2:11  50982112   
4   5              1  11/20/2015 2:12  24738113   

    RACH_Setup_Completion_Success_Rate_AVG  \
0                                 0.992407   
1                                 0.999230   
2                                 0.984591   
3                                 0.994961   
4                                 0.985488   

    Total_RRC_Connection_Setup_Success_Ratio_AVG  \
0                                       0.998720   
1                                       0.993518   
2                                       0.998783   
3                                       0.998095   
4                                       0.998673   

    Total_RRC_Connection_Re_establishment_Success_Ratio_AVG  \
0                                           0.331485          
1                                           0.358130          
2                                           0.310432          
3                                           0.591061          
4                                           0.450843          

    Radio_Bearer_Success_Ratio_AVG   ERAB_SetupSR_AVG  \
0                         0.999198           0.999654   
1                         0.998407           0.998068   
2                         0.999326           0.999253   
3                         0.999203           0.999691   
4                         0.998981           0.999617   

    HO_Success_Ratio_intra_eNB_AVG  \
0                         0.992175   
1                         0.980128   
2                         0.993642   
3                         0.988120   
4                         0.989435   

                             ...                             \
0                            ...                              
1                            ...                              
2                            ...                              
3                            ...                              
4                            ...                              

    Average_Physical_Resource_Block_Usage_UL_AVG  \
0                                       2.029270   
1                                       2.941401   
2                                       1.737991   
3                                       1.960138   
4                                       4.088653   

    Average_Physical_Resource_Block_Usage_DL_AVG  \
0                                       15.12467   
1                                       14.50509   
2                                       10.10685   
3                                       10.62714   
4                                       19.18508   

    Complete_RACH_Setup_Success_Rate_AVG   AGG1_blocked_distribution_rate_AVG  \
0                               0.832560                             0.191129   
1                               0.809881                             0.202040   
2                               0.826034                             0.246141   
3                               0.884707                             0.124238   
4                               0.838161                             0.221814   

    AGG2_blocked_distribution_rate_AVG   AGG4_blocked_distribution_rate_AVG  \
0                             0.213966                             0.257052   
1                             0.190227                             0.202197   
2                             0.235573                             0.274353   
3                             0.169905                             0.169546   
4                             0.191663                             0.188029   

    AGG8_blocked_distribution_rate_AVG  \
0                             0.316564   
1                             0.325704   
2                             0.212420   
3                   

In [79]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13949 entries, 0 to 13948
Data columns (total 22 columns):
ID                                                          13949 non-null int64
 NumComplains                                               13949 non-null int64
 hour_id                                                    13949 non-null object
 LCID                                                       13949 non-null object
 RACH_Setup_Completion_Success_Rate_AVG                     13948 non-null float64
 Total_RRC_Connection_Setup_Success_Ratio_AVG               13947 non-null float64
 Total_RRC_Connection_Re_establishment_Success_Ratio_AVG    13538 non-null float64
 Radio_Bearer_Success_Ratio_AVG                             13947 non-null float64
 ERAB_SetupSR_AVG                                           13947 non-null float64
 HO_Success_Ratio_intra_eNB_AVG                             13799 non-null float64
 Average_CQI_AVG                                            13948 n

In [80]:
data.isnull().sum().sort_values(ascending=False)

 Total_RRC_Connection_Re_establishment_Success_Ratio_AVG    411
 Radio_Bearer_Drop_Ratio_AVG                                380
 HO_Success_Ratio_intra_eNB_AVG                             150
 Average_Physical_Resource_Block_Usage_UL_AVG                80
 ERAB_SetupSR_AVG                                             2
 Total_RRC_Connection_Setup_Success_Ratio_AVG                 2
 Complete_RACH_Setup_Success_Rate_AVG                         2
 Radio_Bearer_Success_Ratio_AVG                               2
 Average_CQI_AVG                                              1
 RACH_Setup_Completion_Success_Rate_AVG                       1
 NumComplains                                                 0
 hour_id                                                      0
 LCID                                                         0
 ERAB_Drop_Ratio_with_UE_Lost_cause_initiated_by_eNB_AVG      0
 AGG_level_block_Rate_AVG                                     0
 Average_Physical_Resource_Block_Usage_D

In [83]:
#To check the number of rows with missing values
data.shape[0]-data.dropna(axis=0).shape[0]

761

In [4]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
'data': range(6)}, columns=['key', 'data'])
print(df)
df.groupby("key").sum()


  key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5


data
key      
A       3
B       5
C       7

In [6]:
rng = np.random.RandomState(0)
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', "C"], \
                   "data1": range(6), "data2": rng.randint(0, 10, 6)},columns = ["key", "data1", "data2"])
print(df)


  key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9


In [7]:
df.groupby("key").aggregate([min,np.median,max])

data1            data2           
      min median max   min median max
key                                  
A       0    1.5   3     3    4.0   5
B       1    2.5   4     0    3.5   7
C       2    3.5   5     3    6.0   9

In [8]:
df.groupby("key").aggregate({"data1":np.median,"data2":max})

data1  data2
key              
A      1.5      5
B      2.5      7
C      3.5      9

In [114]:
df.groupby("key")["data1"].aggregate([min,np.median,max])

min  median  max
key                  
A      0     1.5    3
B      1     2.5    4
C      2     3.5    5

In [116]:
df.groupby('key').filter(lambda x:x['data2'].median() >= 4)


key  data1  data2
0   A      0      5
2   C      2      3
3   A      3      3
5   C      5      9

In [118]:
df.groupby('key').transform(lambda x: x - x.median())


data1  data2
0   -1.5    1.0
1   -1.5   -3.5
2   -1.5   -3.0
3    1.5   -1.0
4    1.5    3.5
5    1.5    3.0